import { useState } from 'react';
import { FileText, Download, Eye, Plus, RefreshCw, Sparkles, Star, Clock, ArrowRight } from 'lucide-react';
import { BreadcrumbNav, type BreadcrumbItem } from './BreadcrumbNav';
import { StatusBadge } from './StatusBadge';
import { CloudBadge } from './CloudBadge';
import { EmptyState, EMPTY_STATES } from './SharedStates';
import { FilterChip } from './FilterChip';
import { PageHeader } from './PageHeader';
import { SummaryMetricCard } from './SummaryMetricCard';
import { useBreakpoint } from '../hooks/useBreakpoint';

interface ReportsPageProps { breadcrumbs: BreadcrumbItem[] }
type ReportType = 'all' | 'cost' | 'security' | 'usage' | 'compliance';

interface Report {
  id: string; title: string; type: ReportType; cloud: 'aws' | 'azure' | 'both';
  date: string; pages: number; status: 'ready'; size: string;
  aiGenerated: boolean; featured?: boolean; summary?: string;
}

const REPORTS: Report[] = [
  {
    id: 'exec', title: 'Q2 2026 Executive Cloud Summary', type: 'cost', cloud: 'both', date: 'Jun 28, 2026',
    pages: 20, status: 'ready', size: '3.2 MB', aiGenerated: true, featured: true,
    summary: 'AI-generated executive brief covering total cloud spend, cost trends, security posture, and 12 actionable optimisation opportunities across AWS and Azure.',
  },
  { id: 'r1', title: 'Monthly Cost Analysis',       type: 'cost',       cloud: 'aws',  date: 'Jun 28, 2026', pages: 12, status: 'ready', size: '1.4 MB', aiGenerated: true  },
  { id: 'r2', title: 'Security Assessment',          type: 'security',   cloud: 'azure', date: 'Jun 27, 2026', pages: 8,  status: 'ready', size: '920 KB', aiGenerated: true  },
  { id: 'r3', title: 'Resource Utilisation Report',  type: 'usage',      cloud: 'aws',  date: 'Jun 25, 2026', pages: 6,  status: 'ready', size: '780 KB', aiGenerated: false },
  { id: 'r4', title: 'Compliance Status Report',     type: 'compliance', cloud: 'azure', date: 'Jun 22, 2026', pages: 15, status: 'ready', size: '2.1 MB', aiGenerated: false },
  { id: 'r5', title: 'Azure Cost Breakdown',         type: 'cost',       cloud: 'azure', date: 'Jun 20, 2026', pages: 9,  status: 'ready', size: '1.1 MB', aiGenerated: true  },
  { id: 'r6', title: 'WAF Security Audit',           type: 'security',   cloud: 'aws',  date: 'Jun 15, 2026', pages: 11, status: 'ready', size: '1.3 MB', aiGenerated: false },
  { id: 'r7', title: 'Cost Forecast — Q3 2026',      type: 'cost',       cloud: 'both', date: 'Jun 8, 2026',  pages: 7,  status: 'ready', size: '860 KB', aiGenerated: true  },
];

const TYPE_LABEL: Record<string, string> = { cost: 'Cost', security: 'Security', usage: 'Usage', compliance: 'Compliance', all: 'All' };
const TYPE_SEV: Record<string, 'success' | 'warning' | 'danger'> = { cost: 'success', security: 'danger', usage: 'warning', compliance: 'warning' };

function AiBadge() {
  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4, fontSize: 10, fontWeight: 700, padding: '2px 7px', borderRadius: 999, backgroundColor: 'var(--dash-accent-tint)', color: 'var(--dash-accent)', letterSpacing: '0.03em' }}>
      <Sparkles size={9} strokeWidth={2} /> AI Generated
    </span>
  );
}

export function ReportsPage({ breadcrumbs }: ReportsPageProps) {
  const [filter, setFilter] = useState<ReportType>('all');
  const bp = useBreakpoint();
  const isMobile = bp === 'mobile';
  const isTablet = bp === 'tablet';

  const featured = REPORTS.find(r => r.featured);
  const nonFeatured = REPORTS.filter(r => !r.featured && (filter === 'all' || r.type === filter));
  const visible = filter === 'all' ? nonFeatured : REPORTS.filter(r => !r.featured && r.type === filter);

  const aiCount  = REPORTS.filter(r => r.aiGenerated).length;
  const cols = isMobile ? '1fr' : isTablet ? '1fr 1fr' : '1fr 1fr 1fr';

  return (
    <div style={{ fontFamily: 'var(--dash-font)' }}>
      <BreadcrumbNav items={breadcrumbs} />
      {/* Header */}
      <PageHeader
        title="Reports"
        description={<>{REPORTS.length} reports {'?'} {aiCount} generated by CloudCEO AI</>}
        actions={<>
          <button style={{ display: 'flex', alignItems: 'center', gap: 5, padding: '8px 14px', borderRadius: 'var(--dash-radius-button)', border: '1px solid var(--dash-border)', background: 'var(--dash-bg-surface)', fontSize: 13, fontWeight: 500, color: 'var(--dash-text-secondary)', cursor: 'pointer', fontFamily: 'var(--dash-font)' }}>
            <RefreshCw size={13} />
          </button>
          <button style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '8px 16px', borderRadius: 'var(--dash-radius-button)', border: 'none', backgroundColor: 'var(--dash-accent)', color: '#FFFFFF', fontSize: 13, fontWeight: 500, cursor: 'pointer', fontFamily: 'var(--dash-font)', transition: 'background-color 0.15s ease' }}
            onMouseEnter={e => { (e.currentTarget as HTMLElement).style.backgroundColor = '#2F4DC4'; }}
            onMouseLeave={e => { (e.currentTarget as HTMLElement).style.backgroundColor = 'var(--dash-accent)'; }}>
            <Plus size={14} /> Generate report
          </button>
        </>}
      />

      {/* ── Featured Executive Summary ── */}
      {featured && (filter === 'all' || filter === 'cost') && (
        <div style={{ backgroundColor: 'var(--dash-bg-surface)', border: '1px solid var(--dash-border)', borderRadius: 'var(--dash-radius-card)', padding: isMobile ? '20px 18px' : '24px 28px', marginBottom: 24, transition: 'border-color 0.15s ease, box-shadow 0.15s ease' }}
          onMouseEnter={e => { const el = e.currentTarget as HTMLElement; el.style.borderColor = 'var(--dash-border-strong)'; el.style.boxShadow = '0 4px 20px rgba(0,0,0,0.06)'; }}
          onMouseLeave={e => { const el = e.currentTarget as HTMLElement; el.style.borderColor = 'var(--dash-border)'; el.style.boxShadow = 'none'; }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 12 }}>
            <div style={{ flex: 1 }}>
              {/* Badges */}
              <div style={{ display: 'flex', gap: 7, alignItems: 'center', marginBottom: 12, flexWrap: 'wrap' }}>
                <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4, fontSize: 10, fontWeight: 700, padding: '2px 8px', borderRadius: 999, backgroundColor: '#FFF8E1', color: '#B8860B', letterSpacing: '0.03em' }}>
                  <Star size={9} strokeWidth={2.5} fill="#B8860B" /> Featured
                </span>
                <AiBadge />
                <StatusBadge label="Cost" severity="success" />
                <CloudBadge variant="aws" />
                <CloudBadge variant="azure" />
              </div>

              <div style={{ fontSize: isMobile ? 17 : 20, fontWeight: 700, color: 'var(--dash-text-primary)', marginBottom: 8, lineHeight: 1.3 }}>{featured.title}</div>
              <div style={{ fontSize: 13, color: 'var(--dash-text-secondary)', lineHeight: 1.7, maxWidth: 640, marginBottom: 16 }}>{featured.summary}</div>

              <div style={{ display: 'flex', gap: 16, alignItems: 'center', flexWrap: 'wrap' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 5, fontSize: 12, color: 'var(--dash-text-muted)' }}>
                  <Clock size={12} /> {featured.date}
                </div>
                <div style={{ fontSize: 12, color: 'var(--dash-text-muted)' }}>{featured.pages} pages · {featured.size}</div>
                <div style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: 11, color: 'var(--dash-accent)', fontWeight: 500 }}>
                  <Sparkles size={11} /> Generated by CloudCEO AI
                </div>
              </div>
            </div>

            {/* Actions */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8, flexShrink: 0 }}>
              <button style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '9px 18px', borderRadius: 'var(--dash-radius-button)', border: 'none', backgroundColor: 'var(--dash-accent)', color: '#FFFFFF', fontSize: 13, fontWeight: 500, cursor: 'pointer', fontFamily: 'var(--dash-font)', whiteSpace: 'nowrap', transition: 'background-color 0.15s ease' }}
                onMouseEnter={e => { (e.currentTarget as HTMLElement).style.backgroundColor = '#2F4DC4'; }}
                onMouseLeave={e => { (e.currentTarget as HTMLElement).style.backgroundColor = 'var(--dash-accent)'; }}>
                <Eye size={14} /> View report <ArrowRight size={13} />
              </button>
              <button style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '9px 18px', borderRadius: 'var(--dash-radius-button)', border: '1px solid var(--dash-border)', background: 'var(--dash-bg-surface)', fontSize: 13, fontWeight: 500, color: 'var(--dash-text-primary)', cursor: 'pointer', fontFamily: 'var(--dash-font)', whiteSpace: 'nowrap' }}>
                <Download size={14} /> Download PDF
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Stats */}
      <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr 1fr' : 'repeat(4, 1fr)', gap: isMobile ? 10 : 14, marginBottom: 20 }}>
        {[
          { label: 'Total reports', value: REPORTS.length.toString(), color: 'var(--dash-text-primary)' },
          { label: 'AI generated', value: aiCount.toString(), color: 'var(--dash-accent)' },
          { label: 'Cost reports', value: REPORTS.filter(r => r.type === 'cost').length.toString(), color: 'var(--dash-success)' },
          { label: 'Security reports', value: REPORTS.filter(r => r.type === 'security').length.toString(), color: 'var(--dash-danger)' },
        ].map(s => (
          <SummaryMetricCard
            key={s.label}
            label={s.label}
            value={s.value}
            valueColor={s.color}
            padding={isMobile ? '12px 14px' : '14px 16px'}
            valueSize={22}
          />
        ))}
      </div>

      {/* Filter tabs */}
      <div style={{ display: 'flex', gap: 6, marginBottom: 16, flexWrap: 'wrap', alignItems: 'center' }}>
        {(['all', 'cost', 'security', 'usage', 'compliance'] as ReportType[]).map(f => (
          <FilterChip key={f} label={f === 'all' ? 'All reports' : TYPE_LABEL[f]} active={filter === f} onClick={() => setFilter(f)} />
        ))}
        <span style={{ fontSize: 12, color: 'var(--dash-text-muted)', marginLeft: 'auto' }}>{visible.length} reports</span>
      </div>

      {/* Report cards grid */}
      {visible.length === 0 ? (
        <EmptyState {...EMPTY_STATES.noReports} actionLabel="Generate report" />
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: cols, gap: 14 }}>
          {visible.map(r => (
            <div key={r.id}
              style={{ backgroundColor: 'var(--dash-bg-surface)', border: '1px solid var(--dash-border)', borderRadius: 'var(--dash-radius-card)', padding: '18px 20px', display: 'flex', flexDirection: 'column', gap: 0, transition: 'border-color 0.15s ease, box-shadow 0.15s ease, transform 0.15s ease' }}
              onMouseEnter={e => { const el = e.currentTarget as HTMLElement; el.style.borderColor = 'var(--dash-border-strong)'; el.style.boxShadow = '0 2px 12px rgba(0,0,0,0.05)'; el.style.transform = 'translateY(-2px)'; }}
              onMouseLeave={e => { const el = e.currentTarget as HTMLElement; el.style.borderColor = 'var(--dash-border)'; el.style.boxShadow = 'none'; el.style.transform = 'none'; }}>
              {/* Icon + badges row */}
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 }}>
                <div style={{ width: 36, height: 36, borderRadius: 9, backgroundColor: 'var(--dash-bg-page)', border: '1px solid var(--dash-border)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <FileText size={18} color="var(--dash-accent)" strokeWidth={1.5} />
                </div>
                <div style={{ display: 'flex', gap: 5, flexWrap: 'wrap', justifyContent: 'flex-end' }}>
                  {r.aiGenerated && <AiBadge />}
                  <StatusBadge label={TYPE_LABEL[r.type]} severity={TYPE_SEV[r.type]} />
                </div>
              </div>

              {/* Title */}
              <div style={{ fontSize: 14, fontWeight: 600, color: 'var(--dash-text-primary)', marginBottom: 10, lineHeight: 1.35 }}>{r.title}</div>

              {/* Meta */}
              <div style={{ display: 'flex', gap: 6, alignItems: 'center', marginBottom: 14, flexWrap: 'wrap' }}>
                {r.cloud === 'both' ? (
                  <div style={{ display: 'flex', gap: 4 }}>
                    <CloudBadge variant="aws" />
                    <CloudBadge variant="azure" />
                  </div>
                ) : (
                  <CloudBadge variant={r.cloud as 'aws' | 'azure'} />
                )}
                <span style={{ fontSize: 11, color: 'var(--dash-text-muted)' }}>{r.date} · {r.pages}p · {r.size}</span>
              </div>

              {/* Actions */}
              <div style={{ display: 'flex', gap: 8, marginTop: 'auto' }}>
                <button style={{ flex: 1, padding: '7px 0', borderRadius: 'var(--dash-radius-button)', border: '1px solid var(--dash-border)', background: 'var(--dash-bg-surface)', fontSize: 12, fontWeight: 500, color: 'var(--dash-text-primary)', cursor: 'pointer', fontFamily: 'var(--dash-font)', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 5, transition: 'border-color 0.12s ease' }}
                  onMouseEnter={e => { (e.currentTarget as HTMLElement).style.borderColor = 'var(--dash-border-strong)'; }}
                  onMouseLeave={e => { (e.currentTarget as HTMLElement).style.borderColor = 'var(--dash-border)'; }}>
                  <Eye size={13} /> View
                </button>
                <button style={{ flex: 1, padding: '7px 0', borderRadius: 'var(--dash-radius-button)', border: 'none', backgroundColor: 'var(--dash-accent)', color: '#FFFFFF', fontSize: 12, fontWeight: 500, cursor: 'pointer', fontFamily: 'var(--dash-font)', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 5, transition: 'background-color 0.15s ease' }}
                  onMouseEnter={e => { (e.currentTarget as HTMLElement).style.backgroundColor = '#2F4DC4'; }}
                  onMouseLeave={e => { (e.currentTarget as HTMLElement).style.backgroundColor = 'var(--dash-accent)'; }}>
                  <Download size={13} /> Download
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
